/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegistrationRouteImport } from './routes/registration'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as AdminAuthenticatedRouteImport } from './routes/admin/_authenticated'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminAuthenticatedIndexRouteImport } from './routes/admin/_authenticated/index'
import { Route as AdminAuthenticatedEventsRouteImport } from './routes/admin/_authenticated/events'
import { Route as AdminAuthenticatedParticipantsRouteImport } from './routes/admin/_authenticated/participants'
import { Route as AdminAuthenticatedScheduleRouteImport } from './routes/admin/_authenticated/schedule'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationRoute = RegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthenticatedRoute = AdminAuthenticatedRouteImport.update({
  id: '/admin/_authenticated',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthenticatedIndexRoute = AdminAuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAuthenticatedRoute,
} as any)
const AdminAuthenticatedEventsRoute =
  AdminAuthenticatedEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedParticipantsRoute =
  AdminAuthenticatedParticipantsRouteImport.update({
    id: '/participants',
    path: '/participants',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedScheduleRoute =
  AdminAuthenticatedScheduleRouteImport.update({
    id: '/schedule',
    path: '/schedule',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/registration': typeof RegistrationRoute
  '/rules': typeof RulesRoute
  '/admin': typeof AdminAuthenticatedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/events': typeof AdminAuthenticatedEventsRoute
  '/admin/participants': typeof AdminAuthenticatedParticipantsRoute
  '/admin/schedule': typeof AdminAuthenticatedScheduleRoute
  '/admin/': typeof AdminAuthenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/registration': typeof RegistrationRoute
  '/rules': typeof RulesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/events': typeof AdminAuthenticatedEventsRoute
  '/admin/participants': typeof AdminAuthenticatedParticipantsRoute
  '/admin/schedule': typeof AdminAuthenticatedScheduleRoute
  '/admin': typeof AdminAuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/registration': typeof RegistrationRoute
  '/rules': typeof RulesRoute
  '/admin/_authenticated': typeof AdminAuthenticatedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/_authenticated/events': typeof AdminAuthenticatedEventsRoute
  '/admin/_authenticated/participants': typeof AdminAuthenticatedParticipantsRoute
  '/admin/_authenticated/schedule': typeof AdminAuthenticatedScheduleRoute
  '/admin/_authenticated/': typeof AdminAuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/registration'
    | '/rules'
    | '/admin'
    | '/admin/login'
    | '/admin/events'
    | '/admin/participants'
    | '/admin/schedule'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/registration'
    | '/rules'
    | '/admin/login'
    | '/admin/events'
    | '/admin/participants'
    | '/admin/schedule'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/registration'
    | '/rules'
    | '/admin/_authenticated'
    | '/admin/login'
    | '/admin/_authenticated/events'
    | '/admin/_authenticated/participants'
    | '/admin/_authenticated/schedule'
    | '/admin/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegistrationRoute: typeof RegistrationRoute
  RulesRoute: typeof RulesRoute
  AdminAuthenticatedRoute: typeof AdminAuthenticatedRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration': {
      id: '/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authenticated': {
      id: '/admin/_authenticated'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authenticated/': {
      id: '/admin/_authenticated/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAuthenticatedIndexRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/events': {
      id: '/admin/_authenticated/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminAuthenticatedEventsRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/participants': {
      id: '/admin/_authenticated/participants'
      path: '/participants'
      fullPath: '/admin/participants'
      preLoaderRoute: typeof AdminAuthenticatedParticipantsRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/schedule': {
      id: '/admin/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/admin/schedule'
      preLoaderRoute: typeof AdminAuthenticatedScheduleRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
  }
}

interface AdminAuthenticatedRouteChildren {
  AdminAuthenticatedEventsRoute: typeof AdminAuthenticatedEventsRoute
  AdminAuthenticatedParticipantsRoute: typeof AdminAuthenticatedParticipantsRoute
  AdminAuthenticatedScheduleRoute: typeof AdminAuthenticatedScheduleRoute
  AdminAuthenticatedIndexRoute: typeof AdminAuthenticatedIndexRoute
}

const AdminAuthenticatedRouteChildren: AdminAuthenticatedRouteChildren = {
  AdminAuthenticatedEventsRoute: AdminAuthenticatedEventsRoute,
  AdminAuthenticatedParticipantsRoute: AdminAuthenticatedParticipantsRoute,
  AdminAuthenticatedScheduleRoute: AdminAuthenticatedScheduleRoute,
  AdminAuthenticatedIndexRoute: AdminAuthenticatedIndexRoute,
}

const AdminAuthenticatedRouteWithChildren =
  AdminAuthenticatedRoute._addFileChildren(AdminAuthenticatedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegistrationRoute: RegistrationRoute,
  RulesRoute: RulesRoute,
  AdminAuthenticatedRoute: AdminAuthenticatedRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
