import { useEffect, useMemo, useRef, useState } from "react";
import type { FormEvent } from "react";
import { Html5Qrcode } from "html5-qrcode";
import { Camera, CheckCircle2, Clock3, Loader2, LogOut, Mail, MessageCircle, QrCode, XCircle } from "lucide-react";
import { supabase } from "./supabase";
import { createFoodCard, uploadFoodCard } from "./foodCard";
import "./App.css";

type FoodToken = { id: string; token: string; full_name: string; email: string; phone: string | null; card_path: string | null; claimed_at: string | null; created_at: string };
type ClaimResult = { result: "claimed" | "already_claimed" | "invalid"; full_name?: string; email?: string; claimed_at?: string };
type FoodEmailLog = { id: string; food_token_id: string; status: "sending" | "sent" | "failed"; error_message: string | null; created_at: string };
const tokenFromScan = (value: string) => value.replace(/^TECHNOVANZA-FOOD:/i, "").trim();
const formatTime = (value: string) => new Date(value).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" });

function App() {
  const [sessionReady, setSessionReady] = useState(false); const [authenticated, setAuthenticated] = useState(false);
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [notice, setNotice] = useState("");
  const [tokens, setTokens] = useState<FoodToken[]>([]); const [emailLogs, setEmailLogs] = useState<FoodEmailLog[]>([]); const [loading, setLoading] = useState(false); const [provisioning, setProvisioning] = useState(false); const [sendingAll, setSendingAll] = useState(false);
  const [scannerOpen, setScannerOpen] = useState(false); const [scanResult, setScanResult] = useState<ClaimResult | null>(null); const [scanning, setScanning] = useState(false); const [sendingId, setSendingId] = useState<string | null>(null);
  const scannerRef = useRef<Html5Qrcode | null>(null);

  const loadTokens = async () => { setLoading(true); const [{ data, error }, { data: logData, error: logError }] = await Promise.all([supabase.from("food_tokens").select("id, token, full_name, email, phone, card_path, claimed_at, created_at").order("created_at", { ascending: false }), supabase.from("food_token_email_log").select("id, food_token_id, status, error_message, created_at").order("created_at", { ascending: false })]); if (error) setNotice(error.message); else setTokens((data ?? []) as FoodToken[]); if (logError) setNotice(logError.message); else setEmailLogs((logData ?? []) as FoodEmailLog[]); setLoading(false); };
  useEffect(() => { supabase.auth.getSession().then(async ({ data }) => { if (data.session) { const { data: admin } = await supabase.from("admin_profiles").select("id").eq("id", data.session.user.id).maybeSingle(); setAuthenticated(Boolean(admin)); if (admin) void loadTokens(); } setSessionReady(true); }); }, []);
  useEffect(() => () => { void scannerRef.current?.stop().catch(() => undefined); }, []);
  const claimed = useMemo(() => tokens.filter((token) => token.claimed_at).length, [tokens]);
  const latestEmailByToken = useMemo(() => { const latest = new Map<string, FoodEmailLog>(); emailLogs.forEach((log) => { if (!latest.has(log.food_token_id)) latest.set(log.food_token_id, log); }); return latest; }, [emailLogs]);

  const login = async (event: FormEvent) => { event.preventDefault(); setNotice(""); const { data, error } = await supabase.auth.signInWithPassword({ email, password }); if (error || !data.user) return setNotice(error?.message ?? "Sign in failed."); const { data: admin } = await supabase.from("admin_profiles").select("id").eq("id", data.user.id).maybeSingle(); if (!admin) { await supabase.auth.signOut(); return setNotice("This account is not authorized for food distribution."); } setAuthenticated(true); void loadTokens(); };
  const provisionTokens = async () => { setProvisioning(true); setNotice(""); const { error } = await supabase.rpc("provision_food_tokens"); if (error) setNotice(error.message); else await loadTokens(); setProvisioning(false); };
  const submitScan = async (scannedValue: string) => { if (!scannedValue || scanning) return; setScanning(true); await scannerRef.current?.stop().catch(() => undefined); const { data, error } = await supabase.rpc("claim_food_token", { p_token: tokenFromScan(scannedValue) }); setScannerOpen(false); setScanResult(error ? { result: "invalid" } : (data as ClaimResult)); await loadTokens(); setScanning(false); };
  const startScanner = async () => { setScanResult(null); setScannerOpen(true); window.setTimeout(async () => { try { const scanner = new Html5Qrcode("food-qr-reader"); scannerRef.current = scanner; await scanner.start({ facingMode: "environment" }, { fps: 10, qrbox: { width: 240, height: 240 } }, submitScan, () => undefined); } catch { setNotice("Camera could not start. Allow camera permission, then try again."); setScannerOpen(false); } }, 50); };
  const sendFoodCard = async (token: FoodToken): Promise<boolean> => { setSendingId(token.id); try { const card = await createFoodCard(token.full_name, token.token); const imageUrl = await uploadFoodCard(token.id, card); const { error } = await supabase.functions.invoke("send-food-token-email", { body: { foodTokenId: token.id, studentName: token.full_name, studentEmail: token.email, imageUrl } }); if (error) throw error; await loadTokens(); return true; } catch (error) { setNotice(error instanceof Error ? error.message : "Could not send food token."); return false; } finally { setSendingId(null); } };
  const sendAllFoodCards = async () => { setSendingAll(true); setNotice(""); let sent = 0; let failed = 0; for (const token of tokens) { if (await sendFoodCard(token)) sent++; else failed++; } setSendingAll(false); setNotice(failed ? `${sent} food QR card(s) sent; ${failed} failed.` : `${sent} food QR card(s) sent.`); };
  const whatsappUrl = (token: FoodToken) => { const phone = token.phone?.replace(/\D/g, ""); if (!phone || phone.length !== 10) return null; const text = `Hi ${token.full_name}, please collect your TECHNOVANZA 2026 food token at the food counter. Show the Food Token QR card sent to your Gmail.`; return `https://wa.me/91${phone}?text=${encodeURIComponent(text)}`; };

  if (!sessionReady) return <div className="center"><Loader2 className="spin" /> Loading food token system…</div>;
  if (!authenticated) return <main className="login"><section><p className="eyebrow">TECHNOVANZA 2026</p><h1>Food Token Admin</h1><p>Secure food distribution scanner for coordinators.</p><form onSubmit={login}><label>Admin Gmail<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required /></label><label>Password<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} required /></label>{notice && <p className="error">{notice}</p>}<button>Sign in</button></form></section></main>;
  return <main className="dashboard"><header><div><p className="eyebrow">TECHNOVANZA 2026</p><h1>Food Token Control</h1></div><button className="secondary" onClick={async () => { await supabase.auth.signOut(); setAuthenticated(false); }}><LogOut size={17} /> Sign out</button></header>{notice && <p className="error banner">{notice}</p>}
    <section className="stats"><article><QrCode /><span>Total tokens<strong>{tokens.length}</strong></span></article><article className="claimed"><CheckCircle2 /><span>Food claimed<strong>{claimed}</strong></span></article><article className="remaining"><Clock3 /><span>Not claimed<strong>{tokens.length - claimed}</strong></span></article></section>
    <section className="actions"><button onClick={startScanner}><Camera size={19} /> Scan food QR</button><button className="secondary" onClick={provisionTokens} disabled={provisioning}>{provisioning ? <Loader2 className="spin" size={18} /> : <QrCode size={18} />} Create food tokens from registrations</button><button className="secondary" onClick={sendAllFoodCards} disabled={sendingAll || !tokens.length}>{sendingAll ? <Loader2 className="spin" size={18} /> : <Mail size={18} />} Send all QR cards</button><button className="secondary" onClick={loadTokens} disabled={loading}>Refresh</button></section>
    <section className="table-wrap"><div className="table-title"><h2>Food claim status</h2><p>Every successful scan saves the exact claim time.</p></div>{loading ? <p>Loading…</p> : <table><thead><tr><th>Name</th><th>Gmail</th><th>Status</th><th>Claimed at</th><th>QR email</th><th>Reminder / card</th></tr></thead><tbody>{tokens.map((token) => <tr key={token.id}><td>{token.full_name}</td><td>{token.email}</td><td><span className={`status ${token.claimed_at ? "yes" : "no"}`}>{token.claimed_at ? "Claimed" : "Not claimed"}</span></td><td>{token.claimed_at ? formatTime(token.claimed_at) : "—"}</td><td>{(() => { const delivery = latestEmailByToken.get(token.id); return <><span className={`status ${delivery?.status === "sent" ? "yes" : delivery?.status === "failed" ? "no" : ""}`}>{delivery?.status === "sent" ? "Sent" : delivery?.status === "failed" ? "Failed" : "Not sent"}</span>{delivery?.error_message && <small className="delivery-error">{delivery.error_message}</small>}</>; })()}</td><td><div className="row-actions">{!token.claimed_at && whatsappUrl(token) && <a href={whatsappUrl(token)!} target="_blank" rel="noreferrer"><MessageCircle size={16} /> WhatsApp</a>}<button className="small" onClick={() => sendFoodCard(token)} disabled={sendingId === token.id}>{sendingId === token.id ? "Sending…" : "Send QR"}</button></div></td></tr>)}</tbody></table>}</section>
    {scannerOpen && <div className="modal"><div className="scanner"><button className="close" onClick={async () => { await scannerRef.current?.stop().catch(() => undefined); setScannerOpen(false); }}>×</button><h2>Scan Food Token</h2><p>Point the camera at the student’s food QR card.</p><div id="food-qr-reader" /></div></div>}
    {scanResult && <div className="modal"><div className={`scanner result ${scanResult.result}`}><button className="close" onClick={() => setScanResult(null)}>×</button>{scanResult.result === "claimed" ? <CheckCircle2 size={52} /> : scanResult.result === "already_claimed" ? <Clock3 size={52} /> : <XCircle size={52} />}<h2>{scanResult.result === "claimed" ? "Food claimed" : scanResult.result === "already_claimed" ? "Food already claimed" : "Invalid food QR"}</h2>{scanResult.full_name && <p><strong>{scanResult.full_name}</strong><br />{scanResult.email}</p>}{scanResult.claimed_at && <p>Claimed on {formatTime(scanResult.claimed_at)}</p>}<button onClick={startScanner}><Camera size={18} /> Scan next student</button></div></div>}
  </main>;
}

export default App;
